### ISSUE TITLE
release version 1.0.0

### ISSUE THREAD

**Issue by PixelJonas** [stevespringett/vulndb-data-mirror#1] opened 2018-12-11 08:19 UTC
I'm currently looking into the dependency-track project. One of my first issues is about the heavy usage of "*-SNAPSHOT" dependencies. For our company use I'd like to create a version which is only relying on release versions, available on the main maven repositories.

It seems all but this dependencies are providing appropriate release versions.

Is there anything I can help with to get version 1.0.0 released for this dependency?

**Comment by stevespringett** [comment] 2018-12-11 17:18
This project was blocked due to an issue with VulnDB that the vendor has just recently fixed. The fix has been implemented, not tested, and the project still is not feature complete - still lacking update synchronization. I likely won't be releasing 1.0.0 until mid-2019 at the earliest.

If you're not using VulnDB however, none of the code in this library will ever be called. In fact, if a vulndb directory doesn't exist in the dependency-track data directory, this library can likely be manually omitted.

**Comment by stevespringett** [comment] 2018-12-11 17:19
Also: refer to https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/tasks/VulnDbSyncTask.java#L71

**Comment by PixelJonas** [comment] 2018-12-20 12:32
my main concern is not the exact number of the project itself but that's it's a SNAPSHOT dependency which may change with every build. 

Is it possible to decrease the version and go for < 1.0.0 releases, to indicate it's not feature-complete project?

**Comment by stevespringett** [comment] 2018-12-20 16:40
-SNAPSHOT already indicates its not complete. No need to alter versions which would be seriously problematic for organizations already using this library.

**Comment by stevespringett** [comment] 2018-12-20 18:24
If reproducibility is what you're after, why don't you just pin to a specific version of a snapshot.

Current:
1.0.0-20180524.022156-17

**Comment by stevespringett** [comment] 2019-09-25 02:28
1.0.0 released

**Closed by stevespringett** 2019-09-25 02:28 UTC
Labels: question
